import type { Metadata } from "next";
import {  Antonio, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-inter'});
const antonio = Antonio({subsets:['latin'],variable:'--font-antonio'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.variable, antonio.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
